version: "3.9"

services:
  clbt:
    image: ghcr.io/missemily2022/clbt:new
    container_name: clbt
    environment:
      - telegram_token=${telegram_token}
      - user_ids=${user_ids}
      - group_ids=${group_ids}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
